### ISSUE TITLE
get error with Line 34

### ISSUE THREAD

**Issue by ChicodelMar** [kubi34/Metamask-Phase-Key-Multiprocess-Brute-Force#3]
Hello, i get this
i paste my API in the text file.

(venv) PS C:\force> python checkerv5.py
Traceback (most recent call last):
  File "checkerv5.py", line 34, in <module>
    ETHAPI, BSCAPI = line.split(':')
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by kubi34** [comment]
Paste your apikeys in APIKeys.txt like this  ETHAPI:BSCAPI
